# Generated by Django 4.1.6 on 2023-02-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_bookingmodel_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='category',
        ),
    ]
