# Generated by Django 4.1.6 on 2023-02-22 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_categorymodel_remove_productmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.categorymodel'),
            preserve_default=False,
        ),
    ]
