# Generated by Django 4.1.6 on 2023-02-22 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_productmodel_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='subcategory',
        ),
    ]
