# Generated by Django 4.1.6 on 2023-02-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_categorymodel_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddToCartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.IntegerField(default=1)),
            ],
        ),
    ]
