# Generated by Django 4.1.6 on 2023-02-25 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_addtocartmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocartmodel',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='addtocartmodel',
            name='total_price',
        ),
    ]
