# Generated by Django 4.1.6 on 2023-02-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_addtocartmodel_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocartmodel',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
