# Generated by Django 4.1.6 on 2023-02-25 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0011_addtocartmodel_foruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartBookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('datentime', models.DateTimeField()),
                ('total_payment', models.CharField(max_length=20)),
                ('services', models.JSONField(default=list)),
                ('BookingTime', models.DateTimeField(auto_now_add=True)),
                ('foruser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
