# Generated by Django 4.1.6 on 2023-02-25 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_remove_contactmodel_name_remove_contactmodel_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='username',
        ),
    ]
