# Generated by Django 4.1.6 on 2023-02-27 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_productmodel_img_productmodel_img2_productmodel_img3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocartmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='addtocartmodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='size',
        ),
        migrations.AddField(
            model_name='addtocartmodel',
            name='item',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='website.productmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addtocartmodel',
            name='size',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
