# Generated by Django 4.1.6 on 2023-02-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_remove_addtocartmodel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocartmodel',
            name='fit',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
