# Generated by Django 4.1.6 on 2023-02-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartbookingmodel',
            name='address',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartbookingmodel',
            name='city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartbookingmodel',
            name='state',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartbookingmodel',
            name='zip',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
