# Generated by Django 4.1.6 on 2023-03-01 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_rename_pass1_customuser_password1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='prod',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='website.productmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password2',
            field=models.CharField(max_length=100),
        ),
    ]
