# Generated by Django 4.1.6 on 2023-03-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_review_prod_alter_customuser_password1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='datentime',
            field=models.DateTimeField(auto_now_add=True, default='2023-01-01 10:10:10'),
            preserve_default=False,
        ),
    ]
