# Generated by Django 4.1.6 on 2023-03-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_review_datentime'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocartmodel',
            name='total_price',
            field=models.IntegerField(default=1),
        ),
    ]
