# Generated by Django 4.1.6 on 2023-03-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_addtocartmodel_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='contact2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
