# Generated by Django 4.1.6 on 2023-03-06 05:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_alter_customuser_address2_alter_customuser_contact2'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocartmodel',
            name='dod',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addtocartmodel',
            name='time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
