# Generated by Django 4.1.6 on 2023-03-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartbookingmodel',
            name='datentime',
            field=models.DateField(),
        ),
    ]
