# Generated by Django 4.1.6 on 2023-03-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_alter_cartbookingmodel_datentime'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartbookingmodel',
            name='OrderStatus',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
