# Generated by Django 4.1.6 on 2023-03-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_alter_cartbookingmodel_orderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartbookingmodel',
            name='dateofdelivery',
            field=models.DateField(default='2023-04-14'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartbookingmodel',
            name='description',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
