# Generated by Django 4.1.6 on 2023-03-10 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_cartbookingmodel_dateofdelivery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartbookingmodel',
            name='datentime',
        ),
    ]
