# Generated by Django 4.1.6 on 2023-03-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_cartbookingmodel_datentime'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartbookingmodel',
            name='quantity',
            field=models.JSONField(default=list),
        ),
    ]
