# Generated by Django 4.1.7 on 2023-03-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_cartbookingmodel_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartbookingmodel',
            name='OrderStatus',
        ),
        migrations.AddField(
            model_name='cartbookingmodel',
            name='order_status',
            field=models.CharField(default='Active', max_length=30),
        ),
    ]
