# Generated by Django 4.1.7 on 2023-03-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_categorymodel_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
