# Generated by Django 4.1.7 on 2023-03-15 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0039_productmodel_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='foruser',
            field=models.ForeignKey(default=32, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
