# Generated by Django 4.1.7 on 2023-03-16 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_review_foruser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='foruser',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='TrackOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.cartbookingmodel')),
            ],
        ),
    ]
